#include "kaomojis.hpp"

const Kaomoji kaomojis[] = {
  {"grinning", "(* ^ ω ^)"},
  {"grinning", "(≧◡≦)"},
  {"grinning_with_arms", "ヽ(o^ ^o)ﾉ"},
  {"grinning", "(*≧ω≦*)"},
  {"grinning_with_arms", "(๑˃ᴗ˂)ﻭ"},
  {"grinning", "(ﾉ≧ڡ≦)"},

  {"sweat_smile", "(´･ᴗ･ ` )"},

  {"laughing", "(o^▽^o)"},
  {"laughing", "(＾▽＾)"},
  {"laughing_with_arms", "ヽ(o＾▽＾o)ノ"},
  {"laughing_with_arms", "\\(^ヮ^)/"},
  {"laughing_blush", "(〃＾▽＾〃)"},

  {"joy", "＼(≧▽≦)／"},
  {"joy", "{*≧∀≦}"},

  {"satisfied", "<(￣︶￣)>"},
  {"satisfied", "(￣ω￣)"},
  {"satisfied", "(─‿‿─)"},
  {"satisfied_laughing", "(￣▽￣)"},
  {"satisfied_laughing_with_arms", "＼(￣▽￣)／"},

  {"smiling_with_arms", "ヽ(*・ω・)ﾉ"},
  {"smiling_blush", "(*^‿^*)"},
  {"smiling", "(◕‿◕)"},
  {"relaxed", "(๑˘︶˘๑)"},
  {"smiling", "(.❛ ᴗ ❛.)"},
  {"smiling_blush", "(=^_^=)"},

  {"wink_heart", " ღゝ◡╹)ノ♡"},

  {"blush_smile", "(*^_^*)"},
  {"flushed", "(•ﾟдﾟ•)"},
  {"blush_closed_eyes", "(〃￣ω￣〃ゞ"},
  {"blush_smile", "(⁄ ⁄•⁄ω⁄•⁄ ⁄)"},
  {"blush_grinning", "(⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)"},
  {"blush_heart", "(´,,•ω•,,)♡"},
  {"blush", "米＾－＾米"},

  {"smug", "(￢‿￢ )"},

  {"heart_eyes_with_arms", "ヽ(♡‿♡)ノ"},
  {"heart_eyes", "(*♡∀♡)"},
  {"heart_eyes", "٩(♡ε♡)۶"},
  {"heart_eyes", "(｡♥‿♥｡)"},
  {"heart_eyes_flower_cheeks", "(✿ ♥‿♥)"},
  {"heart_eyes", "(๑♡⌓♡๑)"},

  {"star_struck", "(✪‿✪)ノ"},
  {"star_struck", "(☆▽☆)"},
  {"star_struck", "(╯✧▽✧)╯"},

  {"kissing_heart", "(っ˘з(˘⌣˘ ) ♡"},
  {"kissing_heart", "σ(≧ε≦σ) ♡"},

  {"kissing", "(ﾉ´ з `)ノ"},
  {"kissing_closed_eyes", "(￣ε￣＠)"},
  {"kissing_closed_eyes", "(￣З￣)"},
  {"kissing", "(ɔˆз(ˆ⌣ˆc)"},

  {"smiling_with_tear", "أ‿أ"},

  {"heart_cheeks", "(♡-_-♡)"},
  {"heart_cheeks", "(´ ω `♡)"},
  {"heart_cheeks_smiling", "(ღ˘⌣˘ღ)"},
  {"heart_cheeks_laughing", "(♡°▽°♡)"},
  {"heart_cheeks", "（♥￫ｏ￩♥）"},

  {"couple", "( ˘⌣˘)♡(˘⌣˘ )"},
  {"blush_heart_arrow", "Σ>―(〃°ω°〃)♡→"},
  {"share_hearts", "♡＼(￣▽￣)／♡"},

  {"flower_cheeks_smiling", "(✿╹◡╹)"},
  {"flower_cheeks", "(◕‿◕✿)"},
  {"flower_cheeks", "(ㆁᴗㆁ✿)"},
  {"flower_cheeks_grinning", "(≖ᴗ≖✿)"},
  {"flower_cheeks", "(✿ヘᴥヘ)"},

  {"OwO", "♡(ŐωŐ人)"},

  {"peace", "y（^ヮ^）y"},

  {"thumbs_up", "d(^^*)"},

  {"expressionless", "|*￣ー￣|"},
  {"expressionless", "（￣ε￣）"},

  {"cry", "(ಥ﹏ಥ)"},
  {"cry", "╥﹏╥"},
  {"cry", "（ｉДｉ）"},
  {"cry", "༼ಢ_ಢ༽"},

  {"sob", ".･ﾟﾟ･(／ω＼)･ﾟﾟ･."},
  {"sob", "｡･ﾟﾟ*(>д<)*ﾟﾟ･｡"},

  {"sad", "(⋟﹏⋞)"},
  {"confused", "(☍﹏⁰)｡"},
  {"frowning", "(-_-)"},
  {"sad_disappointed", "(｡╯︵╰｡)"},
  {"sad_disappointed", "(｡•́︿•̀｡)"},

  {"hugging_sad", "(っ˘̩╭╮˘̩)っ"},

  {"not_sure_tear", "(≖͞_≖̥)"},

  {"unamused", "(；⌣̀_⌣́)"},

  {"unamused", "(￢_￢;)"},
  {"unamused", "(￣ヘ￣)"},
  {"unamused", "(¬▂¬)"},

  {"argueing", "(；￣Д￣)"},
  {"argueing", "(」°ロ°)」"},
  {"argueing", "ヾ( ￣O￣)ツ"},

  {"confounded", "(〃＞＿＜;〃)"},
  {"confounded", "(＞﹏＜)"},

  {"praying", "(￣人￣)"},
  {"praying", "(uωu人)"},

  {"pleading_wink", "(人ゝω・）"},
  {"pleading", "((_　_*"},
  {"pleading", "(」ﾟДﾟ」"},
  {"pleading", "(人ФｴФ)"},

  {"cat", "(=ↀωↀ=)"},
  {"cat", "(⁎˃ᆺ˂)"},
  {"cat", "(=ＴェＴ=)"},
  {"cat", "ฅ(≚ᄌ≚)"},

  {"worried", "(ó﹏ò｡)"},
  {"worried", "(´･_･｀)"},

  {"pout", "( ￣＾￣)"},
  {"pout", "( *｀з´)"},

  {"mad", "ಠ_ಠ"},
  {"mad_with_arms", "ノಠ_ಠノ"},
  {"mad", "ಠ▃ಠ"},

  {"angry", "(⋋▂⋌)"},
  {"angry", "〴⋋_⋌〵"},
  {"angry", "(◔ д◔)"},
  {"angry", "(ʘдʘ╬)"},
  {"angry", "(╬ಠ益ಠ)"},

  {"cheerleader", "⁽⁽⁕◟(.öˬö.)◞⁕⁾⁾"},
  {"cheerleader", "✺◟(∗❛ัᴗ❛ั∗)◞✺"},

  {"party", "┗( ^o^)┛≡┏( ^o^)┓≡┗( ^o^)┛"},
  {"party", "╭(°ㅂ°)╮╰(°ㅂ°)╯╭(°ㅂ°)╮╰(°ㅂ°)╯"},
  {"party", "♪♪＼(^ω^＼)( /^ω^)/♪♪"},

  {"couple_dancing", "♪～(◔◡◔ิ)人(╹◡╹๑)～♪"},
  {"couple_dancing", "ヽ(○｀･v･)人(･v･´●)ﾉ"},

  {"dancing", "┌|≧∇≦|┘"},
  {"dancing", "(〜￣△￣)〜"},
  {"dancing", "ヘ(￣ω￣ヘ)"},
  {"dancing", "₍₍ ◝(・ω・)◟ ⁾⁾"},

  {"take_my_energy", "༼ つ ◕_◕ ༽つ"},
  {"shrugging", "¯\\_(ツ)_/¯"},
  {"sniper", "( ´-ω･)︻┻┳══━一"},
  {"dog", "◤◡ᴥ◡◥ "},
  {"disapproval", "ಠ_ಠ"},
  {"doing_homework", "＿φ(°-°=)"},
  {"thumbs_up", "d-(^.^)z"},
  {"annoyed", "(¬_¬\")"},
  {"flipping_table", "(╯°□°)╯︵ ┻━┻"},
  {"deal_with_it", "(▀̿Ĺ̯▀̿ ̿)"},
  {"distraught", "༼ ༎ຶ ෴ ༎ຶ༽"},
  {"overjoyed", "^_^"},
  {"dancing", "♪┏(・o･)┛♪"},
  {"butterfly", "Ƹ̵̡Ӝ̵̨̄Ʒ"},
  {"kitty_cat", "⋟^≏^⋞"},
  {"table_flips_you", "┬─┬﻿︵/(.□.)╯"},
  {"kirby", "(っ^‿^)っ"},
  {"shocked", "⊙▂⊙"},
  {"polar_bear", "ʕ•͡ᴥ•ʔ"},
  {"kyubey", "／人◕ ‿‿ ◕人＼"},
  {"crazy", "(◐‿◑)﻿"},
  {"feisty", "(ง •̀_•́)ง"},
  {"buddies", "(*^o^)人(^o^*)"},
  {"walrus", "(:3 っ)っ"},
  {"worried", "(´╹〽╹`)"},
  {"wizard", "(∩｀-´)⊃━☆ﾟ.*･｡ﾟ"},
  {"cat", "ฅ(=＾◕ᆺ◕＾=)ฅ"},
  {"hug_me", "⊂((・▽・))⊃"},
  {"scared", ".∵･(ﾟДﾟ)"},
  {"herp_derp", "（。々°）"},
  {"spongebob_squarepants", "|∴め ϖ め∴|"},
  {"sword_fighting", "(´>_●)メ(●_<｀)"},
  {"koala", "ʕ •ᴥ•ʔ"},
  {"frosty_the_snowman", "ᒄ₍⁽ˆ⁰ˆ⁾₎ᒃ♪♬"},
  {"loving", "(ɔ◔‿◔)ɔ ♥"},
  {"but_at_what_cost", "ლ(ಠ益ಠლ)"},
  {"lenny", "( ͡° ͜ʖ ͡°)"},
  {"gimme", "༼ つ ◕_◕ ༽つ"},
  {"painful", "(>_<)"},
  {"whoops", "(－‸ლ)"},
  {"confused", "¯\\(°_o)/¯"},
  {"bowling", "＝( ^o^)ノ___ｏ"},
  {"yoo-hoo", "(ﾉﾟ0ﾟ)ﾉ~"},
  {"ghost", "(((༼•̫͡•༽)))"},
  {"puppy", "U＾ェ＾U"},
  {"flipping_table", "┻━┻ ︵ ヽ(°□°ヽ)"},
  {"flexing", "ᕦ(ò_óˇ)ᕤ"},
  {"superhero", "─=≡Σ(([ ⊐•̀⌂•́]⊐"},
  {"zombie", "[¬º-°]¬"},
  {"celebrating", "ᕕ( ᐛ )ᕗ"},
  {"mustache", "( ￣┏＿┓￣)"},
  {"happy", "^-^"},
  {"staring", "(;￢_￢)"},
  {"punching", "(o￣∇￣)=◯)`ν゜)･"},
  {"fish", "ϵ( 'Θ' )϶"},
  {"squid", "<コ:彡"},
  {"giving_up", "(;´Д`)"},
  {"unimpressed", "（￣～￣）"},
  {"shy", "（/｡＼)"},
  {"monocle", "ಠ_ರೃ"},
  {"running", "ε=┏(ﾟロﾟ;)┛"},
  {"furious", "(ò_ó)"},
  {"hugging", "(>^_^)><(^o^<)"},
  {"huh", "[•.•ิ]"},
  {"pumped", "o(^▽^)o"},
  {"octopus", "Ｃ:。ミ"},
  {"peace", "(^o^)y"},
  {"unamused", "(ㆆ_ㆆ)"},
  {"playing_in_the_snow", "◦°˚\\☺/˚°◦"},
  {"sleeping", "(–˛ — º)"},
  {"emo", "(//_^)"},
  {"anticipation", "(⊃‿⊂)"},
  {"thinking", "(p_-)"},
  {"teddy_bear", "⊂(◜ᴥ◝)つ"},
  {"guilty", "^_^;"},
  {"anime_sweat_drop", "-_-;"},
  {"doing_homework", "＿φ( °-°)/"},
  {"devastated", "(ಥ﹏ಥ)"},
  {"panda", "◖㈠ ω ㈠◗"},
  {"lurk", "┬┴┬┴┤(･_├┬┴┬┴"},
  {"seal", "(ᵔᴥᵔ)"},
  {"excited", "ヽ(★ω★)ノ"},
  {"magic_attack", "(∩｀-´)⊃━☆ﾟ.*･｡ﾟ"},
  {"sobbing", "(╥﹏╥)"},
  {"snubbing", "(´･ω･`)"},
  {"anger", "ლ(ಠ益ಠ)ლ"},
  {"angry_flailing", "ヽ(｀⌒´メ)ノ"},
  {"crying", "T^T"},
  {"pig", "<(^oo^)>"},
  {"freak_out", "ヽ(ﾟДﾟ)ﾉ"},
  {"sleeping_kirby", "૮(-.-)ა"},
  {"content", "˙ ͜ʟ˙"},
  {"resign", "(;-_-)ノ"},
  {"chasing", "(○｀д´)ﾉｼ Σ(っﾟДﾟ)っ"},
  {"bird", "(●∈∋●)"},
  {"hug", "(っ⌒‿⌒)っ"},
  {"ashamed", "(；一_一)"},
  {"darth_vader", "(｡▼皿▼)"},
  {"dj", "d^_^b"},
  {"bear", "⊂(￣(ｴ)￣)⊃"},
  {"oh_no!", "L(´□｀L)"},
  {"inquisitive", "(╭ರ_•́)"},
  {"monocle", "(╭ರ_•́)"},
  {"sleepy", "(- o - ) zzZ ☽"},
  {"whispering", "( ￣ﾉ∇￣)￣ｰ￣)"},
  {"gleeful", "｡◕‿◕｡"},
  {"on_the_phone", "(〃＾∇＾)】"},
  {"disgruntled", "( ͡° ʖ̯ ͡°)"},
  {"clown", "⫷ °⧭° ⫸"},
  {"psycho", "ヘ（。□°）ヘ"},
  {"arm_wrestle", "( `_)乂(_' )"},
  {"groggy", "(-_ゞ"},
  {"bow_and_arrow", "<( ･ｪ-)<}"},
  {"pigtails", "∋∞(●ﾟvﾟ)∞∈"},
  {"bro_pound", "(ó ì_í)=óò=(ì_í ò)"},
  {"scheming", "ಠᴗಠ"},
  {"muscular_person", "ᕦ❍ᴗ❍ᕤ"},
  {"bawling", "ಥ_ಥ"},
  {"skeptical", "(•͡.•͡)"},
  {"rolling_eyes", "◔̯◔"},
  {"imbecile", "(＊☉౪ ⊙｡)ﾉ"},
  {"bread", "ʕʔ"},
  {"hiding", "|д･)"},
  {"scaring", "(☄ฺ◣д◢)☄ฺ"},
  {"smoking", "y(^ o^)y~~"},
  {"hiding_easter_eggs", "( • ∀•)っθΘʘ"},
  {"embarrassed", "(#^.^#)"},
  {"dead_person", "✖‿✖"},
  {"frustrated", "(ᗒᗣᗕ)"},
  {"happy_crying", "(°̥̥̥̥̥̥̥̥ᴗ°̥̥̥̥̥̥̥̥)"},
  {"fighting", "(ง •̀ゝ•́)ง"},
  {"syringe", "-{'''|'''|'''|''']=[]"},
  {"glad", "＼（＾ ＾）／"},
  {"bat", "/|\\( ;,; )/|\\"},
  {"beaten_up", "(*@_＊#)"},
  {"writing", "＿〆(。。)"},
  {"best_buds", "（　＾＾）人（＾＾　）"},
  {"fu_manchu_man", "(￣┏∞┓￣)"},
  {"pumped_up", "ヽ( ★ω★)ノ"},
  {"waving", "( ^_^)／"},
  {"whatever", "¬.¬"},
  {"kiss_me", "( ˘ ³˘)♥"},
  {"pucker_up", "（*＾3＾）"},
  {"lethargic", "(‾ʖ̫‾)"},
  {"surrender", "(ﾉ_ _)ﾉ"},
  {"gift", "(´・ω・)っ由"},
  {"weary", "(´~`)"},
  {"chameleon", "ᘛ⁐̤ᕐᐷ"},
  {"tired", "〠_〠"},
  {"rabbit", "U=･ x ･=U"},
  {"infatuated", "（*´▽｀*）"},
  {"table_tennis", "‎(>o<)ρミ┳┷┳゜"},
  {"whistling", "♪～(￣ε￣；)"},
  {"dreaming", "(_ _)..ooOO"},
  {"deceased", "(✖╭╮✖)"},
  {"painting", "(。･_･)ノ”【】"},
  {"pikachu", "(o^-^o)"},
  {"bear_cub", "(ó㉨ò)"},
  {"boogie_down", "ヽ(⌐■_■)ノ♪♬"},
  {"winnie_the_pooh", "ʕ •́؈•̀)"},
  {"reluctant", "o(´^｀)o"},
  {"surprised", "（￣□￣；）"},
  {"shooting", "(ﾟ皿ﾟ)ｒ┏┳－*"},
  {"thank_you", "＼(-_- )"},
  {"phone", "(((☎)))"},
  {"couple_kissing", "(* ￣)(￣ *) "},
  {"olympic_hammer_throw", "(ﾉ-o-)ﾉ 中"},
  {"cunning", "(¬‿¬)"},
  {"puzzled", "「(°ヘ°)"},
};
